### ISSUE TITLE
Create Model for Evaluations

### ISSUE THREAD

**Issue by zorkpt** [zorkpt/repo_ProjetoGestaoTransacoesImobiliarias#12]
Request to create an Evaluation model. The model should include:

- A reference to the Evaluator object initiating the evaluation.
- Evaluator ID for persistence in JSON.
- A reference to the Property being evaluated.
- Property ID for persistence in JSON.
- An evaluation score or value.
- The date when the evaluation was made.

**Comment by PRS10** [comment]
Done, @zorkpt  check it
