### ISSUE TITLE
 Development of Views and Controllers for Proposals

### ISSUE THREAD

**Issue by zorkpt** [zorkpt/repo_ProjetoGestaoTransacoesImobiliarias#19]
**Description:**
We need to develop views and controllers for handling proposals within our application.

**Tasks:**

- Create Proposal View & Controller: Implement functionality to create new proposals.
- Cancel Proposal View & Controller: Add the ability to cancel existing proposals.
- List Proposals View & Controller: Develop views and controllers to list all proposals, both active and closed.

**Comment by PRS10** [comment]
@zorkpt check it please
