### ISSUE TITLE
 Development of Client Details View with Activity History

### ISSUE THREAD

**Issue by zorkpt** [zorkpt/repo_ProjetoGestaoTransacoesImobiliarias#22]
**Description:**

- Create a comprehensive view for clients that shows their personal details and a complete history of their activities.

**Key Features:**

- Client Personal Details: Display the client's personal and contact information.
- Client Activity History: Include sections for:
- Proposals made by the client.
- Visits scheduled or attended by the client.
- Transactions participated in by the client.
- Additional Client-Specific Options: Add functionalities that cater specifically to client needs.

**Comment by PRS10** [comment]
this one mas a lote of changes, it needs to be check.
